# Generated by Django 5.1.2 on 2024-12-04 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Head', '0003_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('listprice', models.IntegerField()),
                ('price', models.IntegerField()),
                ('price50', models.IntegerField()),
                ('price100', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Head.category')),
                ('materialtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Head.material')),
            ],
        ),
    ]
