# Generated by Django 5.1.2 on 2024-12-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Head', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
