# Generated by Django 5.1.2 on 2024-12-20 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_cart_tb_userid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('orderdate', models.DateField()),
                ('carrier', models.CharField(blank=True, max_length=20, null=True)),
                ('tracking', models.CharField(blank=True, max_length=20, null=True)),
                ('shippingdate', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True)),
                ('paymentdue_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('order_status', models.CharField(blank=True, max_length=20, null=True)),
                ('order_total', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
