# Generated by Django 5.1.2 on 2024-12-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Postal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='State',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
