# Generated by Django 5.1.2 on 2024-12-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_customer_postal_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_tb',
            name='order_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order_tb',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
